language: node_js
node_js:
  - "8"

cache:
  directories:
    - api/node_modules

before_install:
  - cd api && npm update

install:
  - npm install

script:
  - npm run test-ci
  - npm run coveralls
