name: Run tests and coverage

on:
  push:
    branches: [ '*' ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./api
    - run: npm run test-ci
      working-directory: ./api
    - run: npm run coverage
      working-directory: ./api
    - name: Coveralls
      uses: coverallsapp/github-action@v2

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Deploy to Kraag22
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-r --delete-after"
          SOURCE: "api/"
          REMOTE_HOST: "kraag22.com"
          TARGET: "/srv/net_worth"
          REMOTE_USER: "root"
          SCRIPT_AFTER: |
            service net-worth restart
